name: animated_theme_switcher
description: Flutter animated theme switcher, that help to create beautiful transactions during the theme switch.
version: 3.0.0
homepage: https://github.com/kherel/animated_theme_switcher

environment:
  sdk: ">=2.14.4 <4.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0  

flutter:
  uses-material-design: true